### ISSUE TITLE
questions on German reunification example

### ISSUE THREAD

**Issue by kdlin** [OscarEngelbrektson/SyntheticControlMethods#2]
Q1: Does the red dashed line represent the West Germany GDP if there was no reunification? 

Q2: After the reunification, does the actual "West Germany" GDP (the blue solid line) represent the entire Germany GDP? Or still just the West Germany GDP?

**Comment by OscarEngelbrektson** [comment]
Hey @kdlin,

Q1: Yes. The red dashed line is the synthetic control estimate of what West Germany's GDP per capita would have been if reunification never happened.

Q2: Just West Germany. For all time periods, before as well as after reunification, the blue line represents just West Germany's GDP.


Do you have any feedback about the package? I am still working on it and would really appreciate some input :)

**Comment by kdlin** [comment]
Thanks, Oscar. I am new to this SCM topic. One thing that would be very helpful is more explanation on how to prepare data for your package.

David

**Comment by kdlin** [comment]
@OscarEngelbrektson Are you aware of any examples of applying synthetic control for marketing or business analysis? Thanks.

**Comment by OscarEngelbrektson** [comment]
@kdlin,

Sure!

[Here](https://www.youtube.com/watch?v=j5DoJV5S2Ao&ab_channel=PyData) is a talk about how Uber uses synthetic controls to estimate the effect of policy changes.

This paper by [Brodersen et al. (2015)](https://arxiv.org/pdf/1506.00356.pdf) covers a Bayesian time-series variant of the Synthetic Control method that was developed by Google. It includes an example of how it can be used to estimate the effect of a marketing campaign.

Hope this is helpful!

Best,

**Comment by kdlin** [comment]
@OscarEngelbrektson Thank you. Do you have data for these two examples?
