### ISSUE TITLE
NaN data handling

### ISSUE THREAD

**Issue by kdlin** [OscarEngelbrektson/SyntheticControlMethods#7]
In your West Germany Reunification example, the data has a lot of NaN's. Can you please explain how your APIs handle NaN data?

**Comment by OscarEngelbrektson** [comment]
Hey @kdlin,

Thanks for all your feedback - I really appreciate it! I have updated the [user guide](https://nbviewer.jupyter.org/github/OscarEngelbrektson/SyntheticControlMethods/blob/master/examples/user_guide.ipynb) to explain how missing values are treated in Synth() and DiffSynth(). See point 5 under "Data Requirements".

Best,
Oscar

**Comment by kdlin** [comment]
Good work, Oscar.

David
